-- Create Menu Items Table
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  category text not null,
  image_url text,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  CONSTRAINT menu_items_name_unique UNIQUE (name)
);

-- Seed Menu Items (Initial Data)
-- IMPORTANT: Make sure you've uploaded images to Supabase Storage bucket 'menu-images' first!
-- Images should be named: ayam-gunting.jpg, ayam-lidi.jpg, sosej-cheese.jpg
insert into public.menu_items (name, price, category, image_url) values
  ('Ayam Gunting', 10.00, 'Ayam', 'https://pvjtymlmuujfscwijcmy.supabase.co/storage/v1/object/public/menu-images/ayam-gunting.jpg'),
  ('Ayam Lidi', 3.00, 'Ayam', 'https://pvjtymlmuujfscwijcmy.supabase.co/storage/v1/object/public/menu-images/ayam-lidi.jpg'),
  ('Sosej Cheese', 5.00, 'Sosej', 'https://pvjtymlmuujfscwijcmy.supabase.co/storage/v1/object/public/menu-images/sosej-cheese.jpg')
ON CONFLICT (name) DO NOTHING;

-- Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number int not null,
  total_amount numeric not null,
  status text check (status in ('pending', 'completed', 'cancelled')) default 'completed',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items Table
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  name text not null,
  price numeric not null,
  quantity int not null,
  variant text,
  cheese boolean default false,
  remarks text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional, but good practice
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Create Policies (Allow public read/write for now since we are in dev mode/using anon key for everything)
-- In production, you'd lock this down to authenticated users.
create policy "Enable all access for all users" on public.menu_items for all using (true) with check (true);
create policy "Enable all access for all users" on public.orders for all using (true) with check (true);
create policy "Enable all access for all users" on public.order_items for all using (true) with check (true);
